### PR TITLE
Message cost confirmation added via DIVS in HTML

### PR DESCRIPTION
**Pull request by johnjelliott**
Message cost confirmation added - It is coded so that it will update based on settings.config message cost.

### CODE REVIEW

**Comment by mgutierrezc** [comment]
You are trying to merge your branach with `master`, not with `working_space`. Edit your pull req so that you merge with the right branch

**Comment by johnjelliott** [comment]
Not sure how I missed that - I think I hit the enter button before it was done loading

**Comment by johnjelliott** [comment]
Base branched changed to working_space

**Review by mgutierrezc — APPROVED** [review]
Looks good

**Pull request merged**
